// added typed stages to avoid spelling errors when typing stage names across different place
// just add them here and then use Stages(dot)StageName e.g Stages.START
const Stages = {
    START: 'START',
    RETURN: 'RETURN',
    MENU: 'MENU',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    SEND_MONEY: ' SEND_MONEY',
    REGISTERED_USER: 'REGISTERED_USER',
    UNREGISTERED_USER: 'UNREGISTERED_USER',
    R_PHONE_NUMBER: 'R_PHONE_NUMBER',
    TRANSFER_HISTORY: 'TRANSFER_HISTORY',
    R_AMOUNT: ' R_AMOUNT',
    Handle_Send_Money: ' Handle_Send_Money',
    // VISA_CARD_APPLICATION: 'VISA_CARD_APPLICATION',
   WITHDRAWALS: 'WITHDRAWALS',
    MY_ACCOUNT: 'MY_ACCOUNT',
    R_AGENT_NUMBER: 'R_AGENT_NUMBER',
    AMOUNT: 'AMOUNT',
    CONFIRMATION: 'CONFIRMATION',
    AGENT_CODE: 'AGENT_CODE',
    R_PIN_CODE: 'R_PIN_CODE',
    FIRST_MENU: 'FIRST_MENU',
    R_FIRST_NAME: 'R_FIRST_NAME',
    R_LAST_NAME: 'R_LAST_NAME',
    R_GENDER: 'R_GENDER',
    ACCOUNT_TYPE: 'ACCOUNT_TYPE',
    ID_NUMBER: 'ID_NUMBER',
    R_DOB: 'R_DOB',
    R_PIN_CODE: 'R_PIN_CODE',
    VERIFYING_PIN: 'VERIFYING_PIN',
    R_ADDED_BY: 'Stages.R_ADDED_BY',
    DATE_OF_BIRTH: 'DATE_OF_BIRTH',
    C_PHONE_NUMBER: 'C_PHONE_NUMBER',
    R_REGISTERED_BY: 'R_REGISTERED_BY)',
    R_ID_NUMBER: 'R_ID_NUMBER',
    C_PIN_CODE: 'C_PIN_CODE'
 
}

module.exports = Stages;